export const ProgrammingLanguages = {
    "JavaScript": "/svg/javascript.svg",
    "TypeScript": "/svg/typescript.svg",
    "Python": "/svg/python.svg",
    "HTML": "/svg/html.svg",
    "CSS": "/svg/css.svg",
    "Dart": "/svg/dart.svg",
    "Java": "/svg/java.svg",
    "Ruby": "/svg/ruby.svg",
    "Shell": "/svg/shell.svg",
    "C#": "/svg/csharp.svg",
    "Go": "/svg/go.svg",
    "C++": "/svg/c++.svg",
    "C": "/svg/c.svg",
    "PHP": "/svg/php.svg",
    "Swift": "/svg/swift.svg",
    "Kotlin": "/svg/kotlin.svg",
    "Rust": "/svg/rust.svg",
    "Objective-C": "/svg/objectivec.svg",
    "Jupyter Notebook": "/svg/jupyter.svg",
    "R": "/svg/r.svg",
    "TeX": "/svg/tex.svg",
    "Vim script": "/svg/vim.svg",
    "Scala": "/svg/scala.svg",
    "Perl": "/svg/perl.svg",
    "Lua": "/svg/lua.svg",
    "PowerShell": "/svg/powershell.svg",
    "Haskell": "/svg/haskell.svg",
    "Emacs Lisp": "/svg/emacs.svg",
    "Clojure": "/svg/clojure.svg",
    "Groovy": "/svg/groovy.svg",
    "Elixir": "/svg/elixir.svg",
    "Racket": "/svg/racket.svg",
    "Erlang": "/svg/erlang.svg",
    "CoffeeScript": "/svg/coffeescript.svg",
    "Dockerfile": "/svg/docker.svg",
    "Julia": "/svg/julia.svg",
    "Crystal": "/svg/crystal.svg",
    "Nim": "/svg/nim.svg",
    "Haxe": "/svg/haxe.svg",
    "OCaml": "/svg/ocaml.svg",
    "F#": "/svg/fsharp.svg",
};